spring:
  application:
    name: sb_jwt_app


  datasource:
    url: jdbc:mysql://localhost:3306/sbms_jwt_db
    username: root
    password: text

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
    port: 8081