spring:
  application:
    name: sb_jwt_app



  datasource:
    url: jdbc:postgresql://localhost:5432/sbms_jwt_db
    username: root
    password: text
    # driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  



server:
    port: 8081